[font]

# Font Size
size = 12.0

# Font family - common options:
# "JetBrains Mono", "Fira Code", "Source Code Pro", "Ubuntu Mono", "DejaVu Sans Mono"



[font.normal]
family = "CaskaydiaCove Nerd Font"
style = "Regular"


[font.bold]
family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.italic]
family = "CaskaydiaCove Nerd Font"
style = "Italic"

[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]
