require('ericwarren.telescope')
require('ericwarren.tokyonight')
require('ericwarren.lualine')
require('ericwarren.bufferline')
require('ericwarren.nvim-tree')
require('ericwarren.lsp')
require('ericwarren.treesitter')
