# Font
font_family      CaskaydiaCove Nerd Font
bold_font        CaskaydiaCove Nerd Font Bold
italic_font      CaskaydiaCove Nerd Font Italic
bold_italic_font CaskaydiaCove Nerd Font Bold Italic
font_size        18.0

# Window
background_opacity 0.9
hide_window_decorations no
remember_window_size  no
initial_window_width  130c
initial_window_height 40c

# Shell
shell /bin/zsh

# Tokyo Night colors
background  #1a1b26
foreground  #c0caf5
cursor      #c0caf5

# Normal colors
color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6

# Bright colors
color8   #414868
color9   #f7768e
color10  #9ece6a
color11  #e0af68
color12  #7aa2f7
color13  #bb9af7
color14  #7dcfff
color15  #c0caf5

# macOS
macos_option_as_alt yes
